In [1]:
from utils import *
from cnn import *
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
#from tensorflow.examples.tutorials.mnist import input_data
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
def testMnist(arch):    
    X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
    X = scalePixel(X)
    X = arrToImg(X)
    Y = strToIntArr(y)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=42)

    #model = CNN("mnist", architecture_params = arch )
    model = CNN("mnist_1567817952", architecture_params = arch )
    #model.fit(X_train,y_train,batch_sz=100,epochs=20,method="adam", debug=True)
    pred = model.predict(X_test)
    err = error_rate(pred,y_test)
    print("test error: " + str(err))
    print(confusion_matrix(y_test, pred))
    print("\n")
    print(classification_report(y_test,pred))


In [3]:
def main(): 
    arch = [
        {'type':'C','activation':'relu','num_output':64,'kernel_size': (3,3), 'stride': (1,1), 'drop_out': 0.0},
        {'type':'C','activation':'relu','num_output':128,'kernel_size': (3,3), 'stride': (1,1), 'drop_out': 8.3},
        {'type':'P','pool':'max','kernel_size': (2,2), 'stride': (2,2), 'drop_out': 16.7},
        {'type':'C','activation':'relu','num_output':256,'kernel_size': (3,3), 'stride': (1,1), 'drop_out': 0.0},
        {'type':'C','activation':'relu','num_output':128,'kernel_size': (5,5), 'stride': (1,1), 'drop_out':16.7},
        {'type':'P','pool':'max','kernel_size': (5,5), 'stride': (3,3), 'drop_out': 0.0},
        {'type':'C','activation':'relu','num_output':256,'kernel_size': (3,3), 'stride': (1,1), 'drop_out': 0.0},
        {'type':'FC','activation':'relu','num_output':256,'drop_out': 8.3},
        {'type':'FC','activation':'relu','num_output':128,'drop_out': 0.0}, 
        {'type':'T','activation':None}
    ]
    #testfer2013(arch)
    #testfer2013(arch,False)
    testMnist(arch)

In [4]:
main()

Instructions for updating:
Colocations handled automatically by placer.
built CNN
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./models/CNN_mnist_1567817952
{0, 1} 2
test error: 0.8871428571428571


ValueError: Classification metrics can't handle a mix of unknown and binary targets

In [3]:
y_pred=np.load("pred.npy")

In [6]:
y_test=np.load("ytest.npy",allow_pickle=True)

In [12]:
y_test=y_test.astype('float64')

In [13]:
y_test

array([8., 4., 8., 7., 7., 0., 6., 2., 7., 4., 3., 9., 9., 8., 2., 5., 9.,
       1., 7., 8., 0., 0., 0., 3., 6., 3., 6., 1., 6., 9., 7., 6., 0., 8.,
       5., 5., 2., 9., 1., 6., 4., 9., 7., 7., 4., 5., 2., 7., 3., 9., 2.,
       0., 6., 8., 5., 3., 1., 4., 0., 9., 1., 7., 5., 3., 9., 5., 7., 9.,
       6., 0., 1., 7., 3., 0., 4., 3., 4., 3., 5., 6., 6., 6., 8., 2., 7.,
       1., 1., 3., 8., 8., 7., 5., 1., 8., 2., 0., 8., 7., 3., 0., 3., 4.,
       0., 4., 4., 5., 1., 3., 5., 0., 8., 3., 7., 1., 9., 9., 1., 3., 9.,
       1., 5., 7., 8., 4., 8., 1., 2., 0., 9., 9., 1., 6., 3., 9., 3., 5.,
       6., 3., 1., 1., 3., 4., 2., 1., 4., 3., 5., 6., 2., 8., 2., 1., 8.,
       7., 0., 6., 4., 7., 7., 0., 8., 1., 5., 5., 2., 3., 5., 0., 0., 8.,
       0., 9., 1., 0., 7., 6., 4., 2., 2., 8., 2., 5., 7., 3., 6., 6., 2.,
       1., 2., 3., 9., 1., 7., 9., 8., 6., 5., 3., 5., 9., 1., 5., 9., 3.,
       8., 2., 9., 3., 8., 1., 3., 9., 4., 1., 5., 6., 9., 5., 9., 0., 9.,
       1., 4., 5., 1., 1.

In [15]:
err = error_rate(y_pred,y_test)

In [17]:
print("test error: " + str(err)) 

test error: 0.012857142857142857


In [19]:
print(confusion_matrix(y_test, y_pred))

[[69  0  0  0  0  0  0  0  0  0]
 [ 0 78  0  0  0  0  0  0  0  0]
 [ 0  0 64  0  0  0  0  0  0  0]
 [ 0  0  0 87  0  1  0  0  0  0]
 [ 0  0  0  0 63  0  1  0  0  0]
 [ 0  0  0  1  0 62  0  0  0  0]
 [ 0  0  0  0  0  1 66  0  0  0]
 [ 0  0  1  0  0  0  0 66  0  0]
 [ 0  0  1  0  0  0  1  0 68  0]
 [ 0  0  0  0  0  0  0  1  1 68]]


In [21]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        69
         1.0       1.00      1.00      1.00        78
         2.0       0.97      1.00      0.98        64
         3.0       0.99      0.99      0.99        88
         4.0       1.00      0.98      0.99        64
         5.0       0.97      0.98      0.98        63
         6.0       0.97      0.99      0.98        67
         7.0       0.99      0.99      0.99        67
         8.0       0.99      0.97      0.98        70
         9.0       1.00      0.97      0.99        70

    accuracy                           0.99       700
   macro avg       0.99      0.99      0.99       700
weighted avg       0.99      0.99      0.99       700

